# Generated by Django 5.1.4 on 2024-12-26 09:04

from django.db import migrations, models
import uuid

def populate_tracking_code(apps, schema_editor):
    Booking = apps.get_model('myapp', 'Booking')
    for booking in Booking.objects.all():
        booking.tracking_code = uuid.uuid4().hex[:12].upper()
        booking.save()

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_driver_labour_customer_complaint_booking_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.RunPython(populate_tracking_code),  # Populate the field
        migrations.AlterField(
            model_name='booking',
            name='tracking_code',
            field=models.CharField(max_length=12, unique=True),  # Set NOT NULL after population
        ),
    ]
