# Generated by Django 5.1.4 on 2024-12-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_booking_tracking_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='tracking_code',
        ),
    ]
