# Generated by Django 5.1.4 on 2024-12-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_booking_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tracking_code',
            field=models.CharField(default=1, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
