# Generated by Django 5.1.4 on 2024-12-27 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_description_complaint_complaint_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
