# Generated by Django 5.1.4 on 2024-12-30 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/drivers/'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='media/labours/'),
        ),
    ]
