# Generated by Django 5.1.4 on 2025-01-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_driver_img_alter_labour_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('serviceprovider', 'Service Provider'), ('customer', 'Customer')], max_length=20),
        ),
    ]
