# Generated by Django 5.1.4 on 2025-01-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_users_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
        migrations.AlterField(
            model_name='labour',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='labours/'),
        ),
    ]
