# Generated by Django 5.1.4 on 2025-01-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_driver_img_alter_labour_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labour',
            name='img',
            field=models.TextField(blank=True, null=True),
        ),
    ]
