# Generated by Django 5.1.4 on 2025-01-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_driver_img_alter_labour_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='serviceprovider',
            field=models.TextField(default=45),
            preserve_default=False,
        ),
    ]
